-- auto Generated on 2017-10-19 19:50:11 
-- DROP TABLE IF EXISTS `userDO`;
CREATE TABLE `userDO`(
    `name` VARCHAR (50) NOT NULL DEFAULT '' COMMENT 'name',
    `password` VARCHAR (50) NOT NULL DEFAULT '' COMMENT 'password',
    `role` VARCHAR (50) NOT NULL DEFAULT '' COMMENT 'role',
    `id` INT (11) NOT NULL AUTO_INCREMENT COMMENT 'id',
    `created_at` DATETIME NOT NULL DEFAULT '1000-01-01 00:00:00' COMMENT 'createdAt',
    `updated_at` DATETIME NOT NULL DEFAULT '1000-01-01 00:00:00' COMMENT 'updatedAt',
    PRIMARY KEY (`id`)
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT '`userDO`';
